### ISSUE TITLE
Does ECS works with Boto3?

### ISSUE THREAD

**Issue by paragsangoi** [EMCECS/ecs-samples#25]
Hi,

We are trying to access file stored on ECS in Python using Boto3. It is very slow and taking more time then normal file read. Is Boto3 supported by ECS? We are using Python 3.6.

Also What is the fastest way of accessing files from ECS in Python? We want to read file size of 3 to 5 gb into panda data frame.

Thanks a lot in advance
Parag

**Comment by shy950521** [comment]
[Updated](https://github.com/EMCECS/ecs-samples/tree/master/boto3-python-workshop)
